cart_pole_controller:
  ros__parameters:
    type: effort_controllers/JointGroupEffortController
    joints:
       - slider_to_cart
    write_op_modes:
       - slider_to_cart
    state_publish_rate: 25
    action_monitor_rate: 20
    constraints:
      stopped_velocity_tolerance: 0.05
      goal_time: 5

joint_state_controller:
  ros__parameters:
    type: joint_state_controller/JointStateController
    publish_rate: 50
