name: Gazebo ros2 control CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:foxy-desktop
    steps:
    - uses: actions/checkout@v2
    - name: Setup colcon workspace
      id: configure
      run: |
        cd ..
        mkdir -p /home/ros2_ws/src
        cp -r gazebo_ros2_control /home/ros2_ws/src/
        apt-get update && apt-get install -q -y --no-install-recommends \
          dirmngr \
          gnupg2 \
          lsb-release \
          python3-colcon-ros
        cd /home/ros2_ws/src/
        git clone https://github.com/ros-controls/realtime_tools -b ros2_devel
        git clone https://github.com/ros-controls/ros2_control
        git clone https://github.com/ros-controls/ros2_controllers
        git clone https://github.com/ddengster/ros2_control/ -b coffeebot_deps ros2_control_ddengster
        touch ros2_control_ddengster/COLCON_IGNORE
        cp -r ros2_control_ddengster/joint_limits_interface ros2_control_ddengster/transmission_interface  ros2_control
        git clone https://github.com/ros/xacro -b dashing-devel
        sed -i '/rclcpp/d' ros2_control/joint_limits_interface/CMakeLists.txt
        rosdep update
        rosdep install --from-paths ./ -i -y --rosdistro foxy \
          --skip-keys=controller_interface \
          --skip-keys=controller_manager \
          --skip-keys=controller_parameter_server \
          --skip-keys=hardware_interface \
          --skip-keys=joint_limits_interface \
          --skip-keys=joint_state_controller \
          --skip-keys=joint_trajectory_controller \
          --skip-keys=realtime_tools \
          --skip-keys=transmission_interface \
          --skip-keys=xacro
    - name: Build project
      id: build
      run: |
        cd /home/ros2_ws/
        . /opt/ros/foxy/local_setup.sh
        colcon build
    - name: Run tests
      id: test
      run: |
        cd /home/ros2_ws/
        . /opt/ros/foxy/local_setup.sh
        colcon test --event-handlers console_direct+ --packages-select gazebo_ros2_control gazebo_ros2_control_demos
        colcon test-result
